// <auto-generated />
using MarvelCardsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvelCardsWebAPI.Migrations
{
    [DbContext(typeof(MarvelCardsWebAPIContext))]
    partial class MarvelCardsWebAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XF_Prism_MarvelCards.Model.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeroColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroNameLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroNameLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hero","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeroColor = "#C51925",
                            HeroName = "spider man",
                            Image = "spiderman.png",
                            RealName = "peter parker"
                        },
                        new
                        {
                            Id = 2,
                            HeroColor = "#DF8E04",
                            HeroName = "iron man",
                            Image = "ironman.png",
                            RealName = "tony stark"
                        },
                        new
                        {
                            Id = 3,
                            HeroColor = "#5DDF04",
                            HeroName = "This is Test Data",
                            Image = "ironman.png",
                            RealName = "tony stark"
                        },
                        new
                        {
                            Id = 4,
                            HeroColor = "#040DDF",
                            HeroName = "This is Test Data2",
                            Image = "ironman.png",
                            RealName = "tony stark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
